# -*- coding: utf-8 -*-
"""Movie_Recommendation_System_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/149vdAORA-agldvgQvvv72cGLZ6rT9B6X

# 📘 Dokumentasi Proyek
Dokumentasi ini ditambahkan agar setiap tahapan memiliki penjelasan singkat, sesuai Kriteria 2.

## 1) Business Understanding
- **Problem Statements**: kesulitan menemukan film (information overload), kebutuhan personalisasi, dan penemuan judul baru.
- **Goals**: membangun *content-based filtering* dan *collaborative filtering* untuk menghasilkan rekomendasi yang relevan.
- **Solution Approach**: TF‑IDF + cosine untuk konten, neural embedding untuk kolaboratif.

## 2) Data Understanding
- **Sumber**: MovieLens Latest Small.
- **Jumlah**: movies (9.742×3), ratings (100.836×4), 610 pengguna unik.
- **Kondisi**: Tidak ada nilai hilang pada ratings; tidak ada rating di luar rentang; tidak ada duplikat kunci `movieId`.
- **Uraian fitur**: `movieId`, `title`, `genres`, `userId`, `rating`, `timestamp`.

## 3) Data Preparation
- **Handling Missing Values** (hapus bila ada).
- **Preprocessing `genres`**: ganti `|` → spasi untuk TF‑IDF.
- **Normalisasi rating** ke [0,1] untuk model NN.
- **User‑Item Matrix** dan **train/test split (80/20)**.

## 4) Modeling
### Content‑Based
- TF‑IDF (`stop_words='english'`) → cosine similarity → Top‑N.
### Collaborative
- Embedding(user, movie, d=50) → dot → Dense(1, sigmoid).
- Optimizer Adam, Loss MSE, epoch=10, batch=64, val_split=0.2.

## 5) Evaluation
- **Metrik**: Precision, Recall, MAE, RMSE, Precision@K (rumus dijelaskan di laporan).
- **Interpretasi bisnis**: error rendah & precision@K baik → rekomendasi lebih relevan dan efisien.

## 6) Konsistensi Output
- Setelah menjalankan notebook, salin **Top‑10** rekomendasi (CB & CF) dan metrik ke laporan .md agar identik.

# Movie Recommendation System

## Project Overview
Sistem rekomendasi film ini dikembangkan untuk membantu pengguna menemukan film yang sesuai dengan preferensi mereka. Dengan banyaknya pilihan film yang tersedia di platform streaming, pengguna seringkali mengalami kesulitan dalam menemukan konten yang relevan dengan minat mereka.

Proyek ini mengimplementasikan dua pendekatan sistem rekomendasi:
1. **Content-Based Filtering**: Merekomendasikan film berdasarkan kesamaan konten (genre)
2. **Collaborative Filtering**: Merekomendasikan film berdasarkan preferensi pengguna lain

### ℹ️ Tahap: Import & Instalasi
Menyiapkan pustaka yang dibutuhkan untuk EDA, pemodelan, dan visualisasi.
"""

# === Import Library ===
import os
import zipfile
import warnings
from collections import Counter

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import urllib3
from requests.adapters import HTTPAdapter
from urllib3.util import Retry

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from wordcloud import WordCloud

warnings.filterwarnings('ignore')

# Set style untuk visualisasi
plt.style.use('ggplot')
sns.set_palette("husl")

"""# 1. Business Understanding

### ℹ️ Tahap: Unduh / Muat Dataset
Memuat MovieLens; bila gagal, digunakan dataset sampel agar pipeline tetap berjalan.

### Problem Statements
1. Pengguna kesulitan menemukan film yang sesuai dengan preferensi mereka di antara banyaknya pilihan
2. Tidak adanya sistem personalisasi yang dapat merekomendasikan film berdasarkan minat spesifik pengguna
3. Perlunya sistem yang dapat membantu pengguna menemukan film baru yang sesuai dengan selera mereka

### Goals
1. Membangun sistem rekomendasi berbasis konten (Content-Based Filtering)
2. Membangun sistem rekomendasi kolaboratif (Collaborative Filtering)
3. Memberikan rekomendasi film yang relevan untuk pengguna

### Solution Approach
1. **Content-Based Filtering**: Menggunakan fitur genre film untuk menghitung kesamaan antar film
2. **Collaborative Filtering**: Menggunakan rating dari pengguna untuk memprediksi preferensi pengguna lainnya

# 2. Data Understanding

Pada bagian ini, kita akan mendownload dataset langsung dari sumbernya dan melakukan eksplorasi data awal.

### ℹ️ Tahap: EDA (Movies)
Menggali distribusi tahun rilis, genre terpopuler, dan pola umum.
"""

# [3] Unduh & Muat Dataset (MovieLens Latest Small)
# -----------------------------------------------
# Catatan: Untuk menjaga konsistensi output (Top-10 rekomendasi & metrik),
# notebook ini TIDAK membuat dataset sampel. Jika download gagal, pastikan folder
# `ml-latest-small/` (berisi movies.csv & ratings.csv) tersedia di direktori kerja.

MOVIELENS_URL = "https://files.grouplens.org/datasets/movielens/ml-latest-small.zip"
ZIP_NAME = "ml-latest-small.zip"
DATA_DIR = "ml-latest-small"
MOVIES_CSV = os.path.join(DATA_DIR, "movies.csv")
RATINGS_CSV = os.path.join(DATA_DIR, "ratings.csv")

def download_and_extract_movielens(url: str, zip_name: str, data_dir: str) -> bool:
    """Unduh & ekstrak MovieLens. Return True jika sukses."""
    # Session + retry
    session = requests.Session()
    retry = Retry(total=3, backoff_factor=0.5, status_forcelist=[500, 502, 503, 504])
    adapter = HTTPAdapter(max_retries=retry)
    session.mount("http://", adapter)
    session.mount("https://", adapter)

    # Nonaktifkan peringatan SSL (hanya untuk environment yang bermasalah SSL)
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

    print("📥 Mengunduh dataset MovieLens...")
    try:
        resp = session.get(url, timeout=60, verify=False)
        resp.raise_for_status()
        with open(zip_name, "wb") as f:
            f.write(resp.content)

        print("📦 Mengekstrak dataset...")
        with zipfile.ZipFile(zip_name, "r") as z:
            z.extractall(".")
        print("✅ Dataset berhasil diunduh & diekstrak.")
        return True
    except Exception as e:
        print(f"⚠️  Gagal download/ekstrak: {e}")
        return False

# 1) Pastikan dataset tersedia (download jika belum ada)
if not (os.path.exists(MOVIES_CSV) and os.path.exists(RATINGS_CSV)):
    _ok = download_and_extract_movielens(MOVIELENS_URL, ZIP_NAME, DATA_DIR)
else:
    _ok = True

# 2) Load dataset
if not (os.path.exists(MOVIES_CSV) and os.path.exists(RATINGS_CSV)):
    raise FileNotFoundError(
        "movies.csv / ratings.csv tidak ditemukan. "
        "Silakan pastikan folder `ml-latest-small/` ada (movies.csv & ratings.csv), "
        "atau pastikan koneksi internet aktif agar download berhasil."
    )

movies = pd.read_csv(MOVIES_CSV)
ratings = pd.read_csv(RATINGS_CSV)

print(f"🎬 Movies dataset shape: {movies.shape}")
print(f"⭐ Ratings dataset shape: {ratings.shape}")
display(movies.head())
display(ratings.head())

# [4] Data Understanding - Pengecekan Kualitas Data
# ------------------------------------------------
# Mengecek missing values, duplikasi, dan range rating (outlier sederhana)

print("🔎 Missing values (movies):")
print(movies.isnull().sum())

print("\n🔎 Missing values (ratings):")
print(ratings.isnull().sum())

# Duplikasi
dup_movieid = movies['movieId'].duplicated().sum()
dup_ratings_rows = ratings.duplicated().sum()
print(f"\n🔁 Duplikat movieId di movies: {dup_movieid}")
print(f"🔁 Duplikat baris persis di ratings: {dup_ratings_rows}")

# Cek range rating dan step (0.5)
min_rating, max_rating = ratings['rating'].min(), ratings['rating'].max()
unique_steps = np.sort(ratings['rating'].dropna().unique())
step_ok = np.allclose(np.diff(unique_steps), 0.5) or np.allclose(np.unique(np.diff(unique_steps)), [0.5])
out_of_range = ((ratings['rating'] < 0.5) | (ratings['rating'] > 5.0)).sum()

print(f"\n⭐ Range rating: {min_rating} s/d {max_rating}")
print(f"⭐ Jumlah rating di luar rentang [0.5, 5.0]: {out_of_range}")
print(f"⭐ Step rating konsisten 0.5: {step_ok}")

# Simpan ringkasan untuk insight text-cell
summary_data_understanding = {
    "movies_shape": movies.shape,
    "ratings_shape": ratings.shape,
    "missing_movies": int(movies.isnull().sum().sum()),
    "missing_ratings": int(ratings.isnull().sum().sum()),
    "dup_movieid": int(dup_movieid),
    "dup_ratings_rows": int(dup_ratings_rows),
    "min_rating": float(min_rating),
    "max_rating": float(max_rating),
    "out_of_range": int(out_of_range),
    "step_ok": bool(step_ok),
}
summary_data_understanding

"""### ✅ Insight Data Understanding
Dari output pengecekan kualitas data di atas, dapat disimpulkan:

- Tidak ditemukan **missing values** yang mengganggu proses (lihat hasil `movies.isnull().sum()` dan `ratings.isnull().sum()`).
- Tidak ditemukan **duplikasi kunci** pada `movieId` di `movies`, serta tidak ada **baris duplikat persis** di `ratings`.
- Skala **rating** berada pada rentang **0.5–5.0** dan tidak ada nilai di luar rentang tersebut (outlier sederhana), dengan **step 0.5** yang konsisten.

Kesimpulan ini akan dipakai sebagai acuan agar isi laporan (Data Understanding) *match* dengan proses yang dijalankan di notebook.

### Exploratory Data Analysis (EDA) - Movies Dataset
"""

# Tampilkan informasi tentang dataset movies
print("\nMovies dataset info:")
movies.info()
print("\nFirst 5 rows of movies dataset:")
movies.head()

# Cek missing values
print("\nMissing values in movies dataset:")
print(movies.isnull().sum())

# Analisis tahun rilis film
# Ekstrak tahun dari judul film
movies['year'] = movies['title'].str.extract(r'\((\d{4})\)')
movies['year'] = pd.to_numeric(movies['year'], errors='coerce')

# Visualisasi distribusi tahun rilis
plt.figure(figsize=(12, 6))
plt.hist(movies['year'].dropna(), bins=50, edgecolor='black', alpha=0.7)
plt.title('Distribution of Movie Release Years')
plt.xlabel('Release Year')
plt.ylabel('Number of Movies')
plt.grid(True, alpha=0.3)
plt.show()

# Tampilkan statistik tahun rilis
print("\nStatistics of movie release years:")
print(movies['year'].describe())

# Analisis genre film
# Pisahkan genre yang digabungkan dengan pipe (|)
all_genres = movies['genres'].str.split('|').explode()
genres_count = all_genres.value_counts()

# Visualisasi distribusi genre
plt.figure(figsize=(12, 8))
genres_count.plot(kind='barh')
plt.title('Number of Movies by Genre')
plt.xlabel('Count')
plt.ylabel('Genre')
plt.grid(True, alpha=0.3)
plt.show()

# Tampilkan jumlah film per genre
print("Number of movies by genre:")
print(genres_count)

# Word cloud untuk genre
genre_text = ' '.join(all_genres.dropna())
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(genre_text)

plt.figure(figsize=(12, 6))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud of Movie Genres')
plt.show()

"""### ✅ Insight EDA (Movies)
Berdasarkan visualisasi dan statistik tahun rilis di atas:

- Dataset mencakup film dari berbagai tahun rilis, dengan konsentrasi yang lebih besar pada film-film modern (terlihat dari histogram distribusi `year`).
- Genre **Drama** dan **Comedy** tampak dominan (lihat bar chart jumlah film per genre).
- Word cloud membantu melihat variasi genre yang cukup beragam, sehingga fitur `genres` relevan untuk pendekatan **content-based** (TF‑IDF).

### ℹ️ Tahap: EDA (Ratings)
Melihat film terpopuler, rating tertinggi, serta hubungan jumlah rating vs rata-rata.

### Exploratory Data Analysis (EDA) - Ratings Dataset
"""

# [8] EDA - Film Terpopuler dan Terbaik
# -------------------------------------
# Identifikasi film yang paling banyak dirating dan rating tertinggi

print("🏆 Film Terpopuler dan Terbaik")
print("=" * 50)

# Pastikan kita menggunakan movies_clean yang sudah diproses
if 'movies_clean' not in locals():
    movies_clean = movies.copy()

# Analisis jumlah rating per movie
movie_rating_count = ratings['movieId'].value_counts()
print("🎬 Top 10 film paling banyak dirating:")
print(movie_rating_count.head(10))

# Gabungkan dengan data movies untuk mendapatkan judul
top_10_rated_movies_with_titles = pd.DataFrame({
    'movieId': movie_rating_count.head(10).index,
    'rating_count': movie_rating_count.head(10).values
}).merge(movies_clean, on='movieId')

print("\n🎭 Top 10 film paling banyak dirating dengan judul:")
display(top_10_rated_movies_with_titles[['title', 'rating_count']])

# Analisis rating rata-rata per film (minimal 10 rating)
movie_avg_rating = ratings.groupby('movieId')['rating'].agg(['mean', 'count'])
highly_rated_movies = movie_avg_rating[movie_avg_rating['count'] >= 10]  # Ubah threshold menjadi 10

# Reset index untuk menghindari masalah merge
highly_rated_movies_reset = highly_rated_movies.reset_index()

# Top 10 highest rated movies
top_10_highest_rated = highly_rated_movies_reset.nlargest(10, 'mean')

# Gabungkan dengan data movies untuk mendapatkan judul
top_10_highest_rated_with_titles = pd.DataFrame({
    'movieId': top_10_highest_rated['movieId'],
    'avg_rating': top_10_highest_rated['mean'],
    'rating_count': top_10_highest_rated['count']
}).merge(movies_clean, on='movieId')

print("\n🌟 Top 10 film dengan rating tertinggi (min 10 rating):")
display(top_10_highest_rated_with_titles[['title', 'avg_rating', 'rating_count']])

# Visualisasi top films
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# Plot film paling banyak dirating
top_rated = top_10_rated_movies_with_titles.head(5)
ax1.barh(top_rated['title'], top_rated['rating_count'], color='skyblue')
ax1.set_title('Top 5 Most Rated Movies', fontsize=14)
ax1.set_xlabel('Number of Ratings')
ax1.invert_yaxis()

# Plot film dengan rating tertinggi
top_rated_high = top_10_highest_rated_with_titles.head(5)
ax2.barh(top_rated_high['title'], top_rated_high['avg_rating'], color='lightcoral')
ax2.set_title('Top 5 Highest Rated Movies', fontsize=14)
ax2.set_xlabel('Average Rating')
ax2.set_xlim(4, 5)
ax2.invert_yaxis()

plt.tight_layout()
plt.show()

# Analisis hubungan antara jumlah rating dan rata-rata rating
plt.figure(figsize=(10, 6))
plt.scatter(movie_avg_rating['count'], movie_avg_rating['mean'], alpha=0.5, color='purple')
plt.title('Relationship between Number of Ratings and Average Rating', fontsize=14)
plt.xlabel('Number of Ratings')
plt.ylabel('Average Rating')
plt.grid(True, alpha=0.3)

# Tambahkan trend line
z = np.polyfit(movie_avg_rating['count'], movie_avg_rating['mean'], 1)
p = np.poly1d(z)
plt.plot(movie_avg_rating['count'], p(movie_avg_rating['count']), "r--", alpha=0.8)

plt.show()

print("📈 Insight: Film dengan banyak rating cenderung memiliki rating yang lebih tinggi")
print("💡 Ini menunjukkan efek popularity bias dalam sistem rating")

# === EDA Tambahan ===

# Distribusi rating
plt.figure(figsize=(6,4))
ratings['rating'].hist(bins=np.arange(0.25,5.26,0.5), edgecolor='black')
plt.title('Distribusi Rating')
plt.xlabel('Rating')
plt.ylabel('Frekuensi')
plt.show()

# Jumlah rating per film (top 10)
top_counts = ratings['movieId'].value_counts().head(10)
top_counts.plot(kind='bar')
plt.title('Top-10 Film Paling Banyak Dirating')
plt.xlabel('movieId')
plt.ylabel('Jumlah Rating')
plt.show()

# Jumlah rating per user (top 10)
top_users = ratings['userId'].value_counts().head(10)
top_users.plot(kind='bar')
plt.title('Top-10 Pengguna Paling Aktif')
plt.xlabel('userId')
plt.ylabel('Jumlah Rating')
plt.show()

"""### ✅ Insight EDA (Ratings)
Dari EDA pada data rating:

- Distribusi rating menunjukkan nilai **3.0–4.0** cukup dominan, menandakan mayoritas pengguna memberi rating menengah-tinggi.
- Ada pola **popularity bias**: film dengan jumlah rating besar cenderung memiliki rata-rata rating yang juga relatif tinggi (terlihat dari scatter jumlah rating vs rata-rata rating).
- Terdapat variasi aktivitas pengguna (top user paling aktif), yang penting untuk dipertimbangkan pada **collaborative filtering** (data tidak merata).

# 3. Data Preparation

### ℹ️ Tahap: Data Preparation
Membersihkan missing values, membentuk user‑item matrix, normalisasi.

Pada bagian ini, kita akan mempersiapkan data untuk pemodelan sistem rekomendasi
"""

# Data cleaning - handle missing values jika ada
print("Missing values in movies dataset before cleaning:")
print(movies.isnull().sum())

print("\nMissing values in ratings dataset before cleaning:")
print(ratings.isnull().sum())

# Hapus baris dengan missing values
movies_clean = movies.dropna().copy()
ratings_clean = ratings.dropna().copy()

print(f"\nMovies dataset shape after cleaning: {movies_clean.shape}")
print(f"Ratings dataset shape after cleaning: {ratings_clean.shape}")

# Preprocess genres untuk content-based filtering
# Mengganti pipe (|) dengan spasi untuk memudahkan processing
movies_clean['genres'] = movies_clean['genres'].str.replace('|', ' ', regex=False)

# Untuk collaborative filtering, kita perlu membuat user-item matrix
user_item_matrix = ratings_clean.pivot_table(index='userId', columns='movieId', values='rating')
print("User-item matrix shape:", user_item_matrix.shape)

# Isi missing values dengan 0 (tidak ada rating)
user_item_matrix = user_item_matrix.fillna(0)

# Normalize ratings untuk collaborative filtering
scaler = MinMaxScaler()
user_item_matrix_normalized = pd.DataFrame(
    scaler.fit_transform(user_item_matrix),
    columns=user_item_matrix.columns,
    index=user_item_matrix.index
)

# Split data untuk collaborative filtering
train_data, test_data = train_test_split(ratings_clean, test_size=0.2, random_state=42)
print(f"Training data shape: {train_data.shape}")
print(f"Test data shape: {test_data.shape}")

"""### ✅ Insight Data Preparation
Setelah tahap pembersihan dan transformasi:

- Karena pada tahap Data Understanding tidak ditemukan missing values yang signifikan, proses `dropna()` berperan sebagai **safeguard** dan *tidak mengubah* jumlah data secara material (lihat shape sebelum/sesudah cleaning).
- Kolom `genres` diubah dari format pemisah `|` menjadi spasi agar sesuai untuk **TF‑IDF Vectorization**.
- Matriks **user–item** dibentuk dan nilai kosong diisi **0** agar model kolaboratif memiliki representasi numerik yang lengkap.
- Normalisasi rating ke **[0,1]** membantu stabilitas pelatihan model neural network.

# 4. Modeling and Result

### ℹ️ Tahap: Modeling — Content‑Based
TF‑IDF + cosine similarity untuk menghasilkan Top‑N.

### **4.1 Content-Based Filtering**

Pada bagian ini, kita akan membangun sistem rekomendasi berbasis konten menggunakan TF-IDF dan cosine similarity.
"""

# TF-IDF Vectorization for genres
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(movies_clean['genres'])

# Compute cosine similarity
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Create a DataFrame untuk cosine similarity matrix
cosine_sim_df = pd.DataFrame(cosine_sim, index=movies_clean['movieId'], columns=movies_clean['movieId'])

# Create content-based recommendation function
def content_based_recommendations(movie_title, n_recommendations=10):
    """
    Memberikan rekomendasi film berdasarkan kesamaan genre

    Parameters:
    movie_title (str): Judul film yang ingin dicari rekomendasinya
    n_recommendations (int): Jumlah rekomendasi yang ingin ditampilkan

    Returns:
    list: Daftar film yang direkomendasikan
    """
    # Cari movieId berdasarkan title
    movie_match = movies_clean[movies_clean['title'] == movie_title]
    if len(movie_match) == 0:
        return f"Film '{movie_title}' tidak ditemukan dalam dataset."

    movie_idx = movie_match.index[0]
    movie_id = movies_clean.iloc[movie_idx]['movieId']

    # Dapatkan similarity scores untuk film ini dengan semua film lainnya
    sim_scores = list(enumerate(cosine_sim[movie_idx]))

    # Urutkan film berdasarkan similarity score
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Ambil top n recommendations (skip yang pertama karena itu film itu sendiri)
    sim_scores = sim_scores[1:n_recommendations+1]

    # Dapatkan indeks film
    movie_indices = [i[0] for i in sim_scores]

    # Kembalikan judul film yang direkomendasikan
    return movies_clean['title'].iloc[movie_indices].tolist()

# Test content-based recommendations
test_movie = 'Toy Story (1995)'
print(f"Content-Based Recommendations for '{test_movie}':")
recommendations = content_based_recommendations(test_movie)

if isinstance(recommendations, list):
    for i, rec in enumerate(recommendations, 1):
        print(f"{i}. {rec}")
else:
    print(recommendations)

# Visualisasi similarity matrix untuk beberapa film
# Pilih beberapa film populer untuk divisualisasikan
popular_movies = ['Toy Story (1995)', 'Jumanji (1995)', 'Grumpier Old Men (1995)', 'Waiting to Exhale (1995)']

# Dapatkan movieId untuk film-film populer
popular_movie_ids = []
popular_movie_titles = []

for movie in popular_movies:
    match = movies_clean[movies_clean['title'] == movie]
    if len(match) > 0:
        popular_movie_ids.append(match['movieId'].values[0])
        popular_movie_titles.append(movie)

# Buat subset similarity matrix
similarity_subset = cosine_sim_df.loc[popular_movie_ids, popular_movie_ids]

# Visualisasi heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(similarity_subset, annot=True, fmt='.3f', cmap='YlOrRd',
            xticklabels=popular_movie_titles,
            yticklabels=popular_movie_titles)
plt.title('Cosine Similarity Between Popular Movies')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""### ✅ Insight Modeling (Content-Based)
Hasil uji *content-based* untuk film **Toy Story (1995)** menampilkan Top‑10 film dengan genre yang mirip.

- Rekomendasi yang muncul konsisten mengarah ke film bertema **animasi/keluarga/petualangan**, sehingga metode TF‑IDF pada `genres` berhasil menangkap kemiripan konten.
- Keterbatasan: jika sebuah film memiliki genre sangat umum, rekomendasi bisa terlalu luas karena fitur yang dipakai hanya `genres`.

### **4.2 Collaborative Filtering**

Pada bagian ini, kita akan membangun sistem rekomendasi kolaboratif menggunakan neural network dengan embedding layers.

### ℹ️ Tahap: Modeling — Collaborative
Neural embedding (user/movie) untuk memprediksi rating & rekomendasi.
"""

# Prepare data for neural network collaborative filtering
n_users = ratings_clean['userId'].nunique()
n_movies = ratings_clean['movieId'].nunique()

print(f"Number of unique users: {n_users}")
print(f"Number of unique movies: {n_movies}")

# Create user and movie mapping
user_to_index = {user: idx for idx, user in enumerate(ratings_clean['userId'].unique())}
movie_to_index = {movie: idx for idx, movie in enumerate(ratings_clean['movieId'].unique())}

# Build collaborative filtering model
def build_collaborative_model(n_users, n_movies, embedding_size=50):
    """
    Membangun model neural network untuk collaborative filtering

    Parameters:
    n_users (int): Jumlah user unik
    n_movies (int): Jumlah movie unik
    embedding_size (int): Dimensi embedding

    Returns:
    model: Model neural network yang telah dikompilasi
    """
    # Input layers
    user_input = layers.Input(shape=(1,))
    movie_input = layers.Input(shape=(1,))

    # Embedding layers
    user_embedding = layers.Embedding(n_users, embedding_size)(user_input)
    movie_embedding = layers.Embedding(n_movies, embedding_size)(movie_input)

    # Flatten layers
    user_vector = layers.Flatten()(user_embedding)
    movie_vector = layers.Flatten()(movie_embedding)

    # Dot product
    dot_product = layers.Dot(axes=1)([user_vector, movie_vector])

    # Output
    output = layers.Dense(1, activation='sigmoid')(dot_product)

    # Model
    model = keras.Model(inputs=[user_input, movie_input], outputs=output)
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

    return model

# Build model
collab_model = build_collaborative_model(n_users, n_movies)
collab_model.summary()

# Prepare training data
train_user_ids = train_data['userId'].map(user_to_index).values
train_movie_ids = train_data['movieId'].map(movie_to_index).values
train_ratings = train_data['rating'].values / 5.0  # Normalize ratings to 0-1

# Train model
history = collab_model.fit(
    [train_user_ids, train_movie_ids],
    train_ratings,
    batch_size=64,
    epochs=10,
    validation_split=0.2,
    verbose=1
)

# Plot training history
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['mae'], label='Training MAE')
plt.plot(history.history['val_mae'], label='Validation MAE')
plt.title('Model MAE')
plt.xlabel('Epoch')
plt.ylabel('MAE')
plt.legend()
plt.tight_layout()
plt.show()

# Collaborative filtering recommendation function
def collaborative_recommendations(user_id, n_recommendations=10):
    """
    Memberikan rekomendasi film untuk user tertentu berdasarkan collaborative filtering

    Parameters:
    user_id (int): ID user yang ingin diberikan rekomendasi
    n_recommendations (int): Jumlah rekomendasi yang ingin ditampilkan

    Returns:
    list: Daftar film yang direkomendasikan
    """
    # Periksa apakah user_id ada dalam dataset
    if user_id not in user_to_index:
        return f"User ID {user_id} tidak ditemukan dalam dataset."

    # Dapatkan semua movie IDs
    all_movies = ratings_clean['movieId'].unique()

    # Dapatkan movies yang sudah di-rating oleh user
    rated_movies = ratings_clean[ratings_clean['userId'] == user_id]['movieId'].values
    unrated_movies = [movie for movie in all_movies if movie not in rated_movies]

    # Siapkan input untuk prediksi
    user_ids = np.array([user_to_index[user_id]] * len(unrated_movies))
    movie_ids = np.array([movie_to_index[movie] for movie in unrated_movies])

    # Prediksi rating untuk movies yang belum di-rating
    predictions = collab_model.predict([user_ids, movie_ids], verbose=0)

    # Dapatkan top recommendations
    top_indices = predictions.flatten().argsort()[-n_recommendations:][::-1]
    recommended_movie_ids = [unrated_movies[i] for i in top_indices]

    # Dapatkan judul film yang direkomendasikan
    recommended_movies = movies_clean[movies_clean['movieId'].isin(recommended_movie_ids)]['title'].values

    return recommended_movies.tolist()

# Test collaborative recommendations
test_user_id = 1
print(f"Collaborative Recommendations for user {test_user_id}:")
collab_recommendations = collaborative_recommendations(test_user_id)

if isinstance(collab_recommendations, list):
    for i, rec in enumerate(collab_recommendations, 1):
        print(f"{i}. {rec}")
else:
    print(collab_recommendations)

# Tampilkan film yang pernah di-rating oleh user
user_rated_movies = ratings_clean[ratings_clean['userId'] == test_user_id].merge(
    movies_clean, on='movieId').sort_values('rating', ascending=False)

print(f"\nTop 10 movies rated by user {test_user_id}:")
for i, row in user_rated_movies.head(10).iterrows():
    print(f"{row['title']} - Rating: {row['rating']}")

"""### ✅ Insight Modeling (Collaborative)
Pada *collaborative filtering* berbasis neural embedding:

- Kurva **loss/MAE** (training vs validation) membantu memantau apakah model belajar dengan baik atau mulai overfitting.
- Rekomendasi untuk **User 1** dihasilkan dari prediksi rating untuk film yang *belum pernah* dirating oleh user tersebut, sehingga sifatnya lebih personal dibanding content-based.
- Keterbatasan umum: model membutuhkan cukup banyak interaksi rating; untuk user/item baru dapat terjadi **cold-start**.

# 5. Evaluation

Pada bagian ini, kita akan mengevaluasi performa dari kedua model sistem rekomendasi yang telah dibangun.

### **5.1 Evaluation for Content-Based Filtering**

### ℹ️ Tahap: Evaluation
Menghitung metrik (Precision/Recall/MAE/RMSE/Precision@K) dan membahas hasil.
"""

# Precision and Recall for Content-Based (simplified)
def evaluate_content_based(test_movie, recommendations):
    """
    Evaluasi content-based filtering dengan menghitung precision dan recall

    Parameters:
    test_movie (str): Judul film yang diuji
    recommendations (list): Daftar rekomendasi

    Returns:
    tuple: (precision, recall)
    """
    # Dapatkan genre dari film yang diuji
    test_genres = movies_clean[movies_clean['title'] == test_movie]['genres'].values[0]

    # Dapatkan film dengan genre yang sama (sebagai ground truth)
    actual_similar = movies_clean[movies_clean['genres'].str.contains(test_genres.split()[0])]['title'].values

    # Hitung precision dan recall
    relevant = len(set(recommendations) & set(actual_similar))
    precision = relevant / len(recommendations) if len(recommendations) > 0 else 0
    recall = relevant / len(actual_similar) if len(actual_similar) > 0 else 0

    return precision, recall

# Evaluate content-based
test_movie = 'Toy Story (1995)'
recommendations = content_based_recommendations(test_movie)

if isinstance(recommendations, list):
    precision, recall = evaluate_content_based(test_movie, recommendations)

    print(f"Content-Based Evaluation for '{test_movie}':")
    print(f"Precision: {precision:.2f}")
    print(f"Recall: {recall:.2f}")

    # Visualisasi hasil evaluasi
    metrics = ['Precision', 'Recall']
    values = [precision, recall]

    plt.figure(figsize=(8, 5))
    plt.bar(metrics, values, color=['skyblue', 'lightcoral'])
    plt.title('Content-Based Filtering Evaluation Metrics')
    plt.ylabel('Score')
    plt.ylim(0, 1)
    for i, v in enumerate(values):
        plt.text(i, v + 0.01, f'{v:.2f}', ha='center')
    plt.grid(True, alpha=0.3)
    plt.show()
else:
    print(recommendations)

"""### ✅ Insight Evaluation (Content-Based)
Nilai **precision** dan **recall** di atas menunjukkan seberapa banyak rekomendasi yang benar-benar relevan terhadap definisi *ground truth* yang dipakai.

- Jika precision tinggi, berarti mayoritas rekomendasi memiliki kemiripan genre dengan film acuan.
- Recall cenderung kecil karena *ground truth* (daftar film yang dianggap mirip) biasanya sangat besar, sementara rekomendasi hanya Top‑N.

### **5.2 Evaluation for Collaborative Filtering**
"""

# Prepare test data for collaborative filtering
test_user_ids = test_data['userId'].map(user_to_index).values
test_movie_ids = test_data['movieId'].map(movie_to_index).values
test_ratings = test_data['rating'].values / 5.0

# Evaluate collaborative model
test_loss, test_mae = collab_model.evaluate(
    [test_user_ids, test_movie_ids],
    test_ratings,
    verbose=0
)

print(f"Collaborative Filtering Evaluation:")
print(f"Test Loss: {test_loss:.4f}")
print(f"Test MAE: {test_mae:.4f}")

# Calculate RMSE
test_predictions = collab_model.predict([test_user_ids, test_movie_ids], verbose=0)
rmse = np.sqrt(mean_squared_error(test_ratings, test_predictions))
print(f"Test RMSE: {rmse:.4f}")

# Visualisasi metrik evaluasi
metrics = ['Loss', 'MAE', 'RMSE']
values = [test_loss, test_mae, rmse]

plt.figure(figsize=(10, 6))
plt.bar(metrics, values, color=['lightblue', 'lightgreen', 'lightcoral'])
plt.title('Collaborative Filtering Evaluation Metrics')
plt.ylabel('Score')
for i, v in enumerate(values):
    plt.text(i, v + 0.001, f'{v:.4f}', ha='center')
plt.grid(True, alpha=0.3)
plt.show()

# Hitung precision@k untuk collaborative filtering (simplified)
def evaluate_collaborative(user_id, recommendations, k=10):
    """
    Evaluasi collaborative filtering dengan menghitung precision@k

    Parameters:
    user_id (int): ID user yang diuji
    recommendations (list): Daftar rekomendasi
    k (int): Jumlah rekomendasi teratas yang dipertimbangkan

    Returns:
    float: Precision@k
    """
    # Dapatkan rating tertinggi dari user (sebagai ground truth)
    top_rated_movies = ratings_clean[ratings_clean['userId'] == user_id].nlargest(k, 'rating')['movieId'].values
    top_rated_titles = movies_clean[movies_clean['movieId'].isin(top_rated_movies)]['title'].values

    # Hitung precision@k
    relevant = len(set(recommendations[:k]) & set(top_rated_titles))
    precision_at_k = relevant / k

    return precision_at_k

# Evaluate collaborative filtering
test_user_id = 1
collab_recommendations = collaborative_recommendations(test_user_id, n_recommendations=20)

if isinstance(collab_recommendations, list):
    precision_at_10 = evaluate_collaborative(test_user_id, collab_recommendations, k=10)
    precision_at_5 = evaluate_collaborative(test_user_id, collab_recommendations, k=5)

    print(f"Precision@5 for Collaborative Filtering (User {test_user_id}): {precision_at_5:.2f}")
    print(f"Precision@10 for Collaborative Filtering (User {test_user_id}): {precision_at_10:.2f}")

    # Visualisasi precision@k
    k_values = [5, 10]
    precision_values = [precision_at_5, precision_at_10]

    plt.figure(figsize=(8, 5))
    plt.plot(k_values, precision_values, marker='o', linestyle='-', color='purple')
    plt.title(f'Precision@K for Collaborative Filtering (User {test_user_id})')
    plt.xlabel('K')
    plt.ylabel('Precision@K')
    plt.ylim(0, 1)
    plt.grid(True, alpha=0.3)
    plt.show()
else:
    print(collab_recommendations)

"""### ✅ Insight Evaluation (Collaborative) + Alasan Precision@K = 0
Pada notebook ini, **Precision@K** dihitung dengan membandingkan:

- **Rekomendasi**: film yang *belum* dirating user (unrated movies), diambil Top‑K dari prediksi model.
- **Ground truth**: Top‑K film dengan rating tertinggi yang *sudah* dirating user (rated movies).

Karena rekomendasi **secara sengaja mengecualikan** film yang sudah pernah dirating, maka **irisan (overlap) antara rekomendasi dan ground truth menjadi 0**, sehingga Precision@K untuk User 1 bisa bernilai **0.00**.

**Perbaikan evaluasi yang lebih tepat** (saran untuk pengembangan):
- Gunakan *held-out test set per user*: sembunyikan sebagian film yang dirating (mis. rating ≥ 4) sebagai item relevan, lalu cek apakah item tersebut muncul di Top‑K rekomendasi.
- Atau gunakan metrik ranking seperti **HitRate@K / Recall@K / NDCG@K** yang memang dirancang untuk tugas rekomendasi Top‑N.

# 6. Conclusion

Berdasarkan hasil implementasi dan evaluasi, dapat disimpulkan bahwa:

1. **Content-Based Filtering** bekerja dengan baik untuk merekomendasikan film berdasarkan kesamaan genre. Precision yang dicapai cukup tinggi, menunjukkan bahwa rekomendasi yang diberikan relevan dengan film yang dijadikan acuan.

2. **Collaborative Filtering** berhasil mempelajari pola preferensi pengguna dari data rating. Meskipun metrik evaluasi seperti MAE dan RMSE menunjukkan adanya error dalam prediksi rating, model ini masih dapat memberikan rekomendasi yang cukup baik.

3. Kedua pendekatan memiliki kelebihan dan kekurangan masing-masing:
   - Content-Based Filtering: Tidak memerlukan data dari pengguna lain, tetapi terbatas pada fitur yang tersedia
   - Collaborative Filtering: Dapat menemukan hubungan yang tidak terduga, tetapi mengalami cold start problem untuk user/item baru

4. Untuk pengembangan selanjutnya, dapat dipertimbangkan untuk menggabungkan kedua pendekatan menjadi hybrid recommendation system untuk mendapatkan kelebihan dari kedua metode.
"""

# Simpan model untuk penggunaan di masa depan
collab_model.save('movie_recommendation_model.h5')
print("Model saved successfully!")

# Simpan mapping untuk user dan movie
import pickle
with open('user_to_index.pkl', 'wb') as f:
    pickle.dump(user_to_index, f)
with open('movie_to_index.pkl', 'wb') as f:
    pickle.dump(movie_to_index, f)
print("Mappings saved successfully!")

# Simpan cosine similarity matrix untuk content-based filtering
np.save('cosine_sim_matrix.npy', cosine_sim)
print("Cosine similarity matrix saved successfully!")

"""# 7. References

1. MovieLens Dataset: https://files.grouplens.org/datasets/movielens/ml-latest-small.zip
2. Ricci, F., Rokach, L., & Shapira, B. (2011). Introduction to Recommender Systems Handbook.
3. TensorFlow Documentation: https://www.tensorflow.org/recommenders
4. Scikit-learn Documentation: https://scikit-learn.org/stable/
"""

# Commented out IPython magic to ensure Python compatibility.
# Info Versi Library
# -----------------------
# Menampilkan informasi versi library yang digunakan

print("📦 Info Versi Library")
print("=" * 50)

# Import library tambahan untuk versi
import sklearn
import seaborn as sns
from wordcloud import WordCloud
import matplotlib

print("Library versions:")
print(f"Pandas: {pd.__version__}")
print(f"Numpy: {np.__version__}")
print(f"Scikit-learn: {sklearn.__version__}")
print(f"TensorFlow: {tf.__version__}")
print(f"Matplotlib: {matplotlib.__version__}")
print(f"Seaborn: {sns.__version__}")

# Untuk wordcloud, kita perlu cara berbeda
try:
    # Coba beberapa cara untuk mendapatkan versi wordcloud
    import pkg_resources
    wordcloud_version = pkg_resources.get_distribution("wordcloud").version
    print(f"WordCloud: {wordcloud_version}")
except:
    print("WordCloud: version info not available")

print("\n🐍 Python version:")
import sys
print(sys.version)

# Tampilkan info environment
print("\n🌐 Environment info:")
print(f"Platform: {sys.platform}")
print(f"Python executable: {sys.executable}")

# Gunakan watermark jika tersedia
try:
#     %load_ext watermark
    print("\n💧 Watermark info:")
#     %watermark --iversions
except:
    print("\n⚠️  Watermark extension tidak tersedia")
